### ISSUE TITLE
Get IP input thoughts

### ISSUE THREAD

**Issue by giancarlopetrini** [Keimille/Scripts-and-Automation#1]
https://github.com/Keimille/Scripts-and-Automation/blob/033e04cc7f8af6d2feb55ca2d06351dbc9159536/Boto3/vpgautomation.py#L29-L35

-`raw_input()` looks like it's only for python 2.x. Keep in mind for 3.x it's just `input()`
- if the input fails the conditional, it'll print the warning, but won't halt execution, so you'll get an aws error
- probably some module already out there to validate ip addresses, but for now you can condense the conditional like this:
```
onPremPublic = input() # raw_input()

if (len(onPremPublic)) >= 7 and (len(onPremPublic)) <= 15:
    print("Thank you!")
else:
  print("bob")
  raise ValueError('invalid ip address')

print("completed")
```

If you run this, completed will never show, but bob will if the value fails

**Comment by Keimille** [comment]
-`input()` doesn't handle the input correctly in my version 2.7. I can update to 3 and try the code again. As of now `input()` raises a syntax error when entering IP addresses. 

There is an ipaddress module in python 3.7 where I may be able to do the following:  `ipaddress.ip_address(input())`. I'll have to play around with it and see, but ultimately updating to python 3 would be a good option

**Comment by Keimille** [comment]
Looked at this again but this half of the code works with Python3 so far:

```
import json
import boto3
import ipaddress
#import boto.vpc

ec2 = boto3.resource('ec2', region_name='us-east-1')
client = boto3.client('ec2')


# add tags later
filters = [{'Name': 'tag:Name', 'Values': ['*']}]

vpcs = list(ec2.vpcs.filter(Filters=filters))

for vpc in vpcs:
    response = client.describe_vpcs(
        VpcIds=[
            vpc.id,
        ]
    )
    #print(json.dumps(response, sort_keys=True, indent=4))

VPCforVPN = vpc.id
# print(VPCforVPN)

# conn = boto.vpc.connect_to_region('us-east-1')

print("Please enter the customer public IP address")

onPremPublic = ipaddress.ip_address(input())
```

**Comment by giancarlopetrini** [comment]
nice! I wasn't saying you had to role to python3. and you could look at using a `virtualenv` to manage python versions: https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/. But i did just want to point that out. Unfortunately the version split in python seems more cumbersome than in other languages. 

The main takeaway, though, was more about condensing the conditional so that your raising an exception/halting execution (or can re-prompt if you want) if you already know that aws will spit it back out. 

In a larger code base, you'd probably pass it to an error handler, or wrap the method in a `try except` block. https://www.w3schools.com/python/python_try_except.asp

**Comment by Keimille** [comment]
Fixed the issues outlined hear by using and updating code for boto3 and Python3. Ran and confirmed calls to the API without any errors. Code is merged to the master now.
